version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.9.6
    steps:
      - run:
          command: pip install -r requirements.txt
      - run:
          command python -m unittest

